# Generated by Django 4.2.1 on 2023-05-29 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('address', models.TextField(max_length=250)),
                ('dob', models.DateField(max_length=11)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(max_length=11)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('address', models.TextField(max_length=250)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')])),
                ('account', models.IntegerField(choices=[(0, 'Fixed Deposit'), (3, 'Recurring Deposit'), (1, 'Saving Account'), (2, 'Current Account')])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fedbank.branch')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fedbank.country')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fedbank.country'),
        ),
    ]
